### ISSUE TITLE
编译成功后运行 dtdt.exe 报错：应用程序无法正常启动(0xc000007b)，请单击“确定”关闭应用程序。

### ISSUE THREAD

**Issue by pingxiangren** [huifeng-kooboo/DT#6]
### 构建流程
- 按步骤编译 main.pro 再编译 plugins.pro（编译时先构建 main.pro 会先构建失败， QTC 编译错误提示 make 失败，然后构建 plugins.pro 成功，最后回到 main.pro 编译就成功了）
### 图片
![error](https://github.com/huifeng-kooboo/DT/assets/77879226/b0691ffb-0f28-4de2-a50b-14f37300a25c)
### 尝试解决
网上搜了很多，装各种修复软件都无效，还把我 VMware 给搞打不开了（报同样的错误），后来用 `All_In_One_Runtimes_3.9.2.1` 修复了 VMware 的报错，`dtdt.exe` 的报错依旧还在。
### 建议
博主搞个 QQ 群，给个 QQ 群号行不行，这张微信群二维码早过期了...

**Comment by pingxiangren** [comment]
### 问题定位
- 缺少 VC 相关 dll 文件。
### 解决办法
[Qt 打包发布程序，解决找不到msvcp140.dll等动态库问题正确方案](https://blog.csdn.net/no_say_you_know/article/details/126360830)
> 按照博客的第一种办法做，简单高效。

**Comment by huifeng-kooboo** [comment]
这个定位问题 我本身的depends 依赖库里 有包含这些文件可以直接用的。可以加作者微信：ytouching
